// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
// demographics/control.js
//
// copyright (c) 2014 Douglas Rau
// all rights reserved.

var racial_pct={isolated:[96,2,1],mixed:[79,9,5,3,2,1,1],integrated:[37,20,18,10,7,5,3]},races=["Human","Halfling","Elf","Dwarf","Gnome","Half-elf","Half-orc"],race_plural={Human:"humans",Halfling:"halflings",Elf:"elves",Dwarf:"dwarves",Gnome:"gnomes","Half-elf":"half-elves","Half-orc":"half-orcs"},town_data={thorp:{gp_limit:40,pow_mod:-1,lvl_mod:-3},hamlet:{gp_limit:100,pow_mod:0,lvl_mod:-2},village:{gp_limit:200,pow_mod:1,lvl_mod:-1},small_town:{gp_limit:800,pow_mod:2,lvl_mod:0},large_town:{gp_limit:3E3,
pow_mod:3,lvl_mod:3},small_city:{gp_limit:15E3,pow_mod:4,lvl_mod:6,roll:2},large_city:{gp_limit:4E4,pow_mod:5,lvl_mod:9,roll:3},metropolis:{gp_limit:1E5,pow_mod:6,lvl_mod:12,roll:4}},class_data={Barbarian:{level:"1d4"},Bard:{level:"1d6"},Cleric:{level:"1d6"},Druid:{level:"1d6"},Fighter:{level:"1d8"},Monk:{level:"1d4"},Paladin:{level:"1d3"},Ranger:{level:"1d3"},Rogue:{level:"1d8"},Sorcerer:{level:"1d4"},Wizard:{level:"1d4"},Adept:{level:"1d6","1st_pct":0.5},Aristocrat:{level:"1d4","1st_pct":0.5},Commoner:{level:"4d4",
"1st_pct":91},Expert:{level:"3d4","1st_pct":3},Warrior:{level:"2d4","1st_pct":5}};stat_fmt.by_class=stat_fmt.table;stat_fmt.class_head='<th class="right">Level:</th>';stat_fmt.class_th='<th class="right">#{level}</th>';stat_fmt.class_col='<td class="key">#{class}</td>';stat_fmt.class_td='<td class="right">#{text}</td>';
function init_races(){$("racial_mix").selectedIndex=rand($("racial_mix").options.length);Event.observe("racial_mix","change",race_reaction);$("primary_race").selectedIndex=rand($("primary_race").options.length);Event.observe("primary_race","change",race_reaction);race_reaction()}function race_reaction(){update_race_desc()}
function update_race_desc(){var a=$("racial_mix").getValue(),b=$("primary_race").getValue();stat_fmt.race_desc=stat_fmt["race_desc-"+a];a=enum_by_race(a,b);a=race_desc_obj(a);update_stat("race_desc",a)}function enum_by_race(a,b){var c=races.without(b);c.unshift(b);var d={order:c.clone(),"enum":[],total:0};racial_pct[a].each(function(e){var f=c.shift();d["enum"].push(f);d.total+=e;d[f]=e});if(c.length){d.other=c;d.other_pct=100-d.total}return d}
function race_desc_obj(a){var b=a["enum"].clone(),c=b.shift();c=fmt_race_pct(c.toLowerCase(),a[c]);b=b.map(function(e){return fmt_race_pct(race_plural[e],a[e])});if(a.other){var d=fmt_race_pct("other races",a.other_pct);b=b.join(", ")+" and "+d}else{d=b.pop();b=b.join(", ")+" and "+d}return{primary:c,other:b}}function fmt_race_pct(a,b){a={race:a,pct:b};return stat_fmt.race_pct.evaluate(a)}
function update_gp_limit(){var a=$("town_pop").intValue(),b=town_desc(a),c=town_size(a);c=town_data[c].gp_limit;a=Math.floor(c/2*(a/10));b={desc:b,limit:gp_value(c),total:gp_value(a)};update_stat("gp_limit",b)}function town_size(a){return a>25E3?"metropolis":a>12E3?"large_city":a>5E3?"small_city":a>2E3?"large_town":a>900?"small_town":a>400?"village":a>80?"hamlet":"thorp"}function gp_value(a){return commafy(a)+" gp"}
function update_power_centers(){var a=$("town_pop").intValue(),b=town_size(a);a=town_data[b].roll;a=a>0?a:1;b=town_data[b].pow_mod;var c=[],d;for(d=0;d<a;d++){var e=power_desc(b);c.push(fmt_power_center(e,power_align()));e=="conventional"&&rand(100)<5&&c.push(fmt_power_center("monstrous",power_align()))}a={list:fmt_ol(c)};update_stat("power_centers",a)}function power_desc(a){a=parseInt(roll_dice("1d20"))+a;return a>18?"magical":a>13?"nonstandard":"conventional"}
function power_align(){var a=parseInt(roll_dice("1d100"));return a>98?"ce":a>90?"ne":a>64?"le":a>63?"cn":a>61?"tn":a>41?"ln":a>39?"cg":a>35?"ng":"lg"}function fmt_power_center(a,b){a={desc:load_desc("power-"+a),align:load_desc("align-"+b)};return stat_fmt.power_center.evaluate(a)}function load_desc(a){return $(a).innerHTML.trim()}function update_by_class(){var a=$("town_pop").intValue(),b=town_size(a);a=enum_by_class(a,b);a={rows:class_rows(a)};update_stat("by_class",a)}
function enum_by_class(a,b){var c=town_data[b].roll,d=c>0?c:1,e=town_data[b].lvl_mod,f={},i=a;$H(class_data).keys().each(function(h){f[h]=default_class_poll();var m=class_data[h].level,j=class_data[h]["1st_pct"];j=j?1:0;var k;for(k=0;k<d;k++)for(var g=parseInt(roll_dice(m))+e,l=1;g>j;){if(g<=20){f[h][g]+=l;i-=l}g=Math.floor(g/2);l*=2}});if(i>0)f=enum_npc_1st(f,i);return $H(f)}function default_class_poll(){var a={},b;for(b=1;b<=20;b++)a[b]=0;return a}
function enum_npc_1st(a,b){var c=b;$H(class_data).keys().each(function(d){if(class_data[d]["1st_pct"]){var e=class_data[d]["1st_pct"]/100;e=Math.round(c*e);a[d][1]=e;b-=e}});if(b!=0)a.Commoner[1]+=b;return a}function class_rows(a){var b=a.keys(),c=[class_head()],d;for(d=0;d<b.length;d++){var e=b[d],f=a.get(e);c.push(class_row(e,f))}return c.join("")}
function class_head(){var a=stat_fmt.class_head.evaluate({}),b;for(b=1;b<=20;b++)a+=stat_fmt.class_th.evaluate({level:b});return stat_fmt.table_row.evaluate({cols:a})}function class_row(a,b){a={"class":a};a=stat_fmt.class_col.evaluate(a);var c;for(c=1;c<=20;c++){var d=b[c];d=d>0?d:"&nbsp;";a+=stat_fmt.class_td.evaluate({text:d})}return stat_fmt.table_row.evaluate({cols:a})}add_annex_fn("init_form",init_races);add_annex_fn("recalc_town",update_race_desc);add_annex_fn("recalc_town",update_gp_limit);
add_annex_fn("recalc_town",update_power_centers);add_annex_fn("recalc_town",update_by_class);
