// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
// demographics/control.js
//
// copyright (c) 2014 Douglas Rau
// all rights reserved.

var kingdom_form_id="kingdom_form",town_form_id="town_form",rpc_url="/fantasy/random/rpc.cgi",stat_fmt={},trade_sv={Bakers:800,Barbers:350,Bathers:1900,"Beer-sellers":1400,Blacksmiths:1500,Bleachers:2100,Bookbinders:3E3,Booksellers:6300,"Buckle Makers":1400,Butchers:1200,Carpenters:550,Chandlers:700,"Chicken Butchers":1E3,Coopers:700,Copyists:2E3,Cutlers:2300,Doctors:1700,Fishmongers:1200,Furriers:250,Glovemakers:2400,"Harness-makers":2E3,Hatmakers:950,"Hay Merchants":2300,Illuminators:3900,Inns:2E3,
Jewelers:400,Locksmiths:1900,"Magic Shops":2800,Maidservants:250,Masons:500,Mercers:700,"Old Clothes":400,Painters:1500,Pastrycooks:500,Plasterers:1400,Pursemakers:1100,Roofers:1800,Ropemakers:1900,Rugmakers:2E3,Saddlers:1E3,Scabbardmakers:850,Sculptors:2E3,Shoemakers:150,"Spice Merchants":1400,Tailors:250,Tanners:2E3,Taverns:400,Watercarriers:850,Weavers:600,"Wine-sellers":900,Woodcarvers:2400,Woodsellers:2400};stat_fmt.table='<table class="smaller">#{rows}</table>';stat_fmt.table_row="<tr>#{cols}</tr>";
stat_fmt.by_trade=stat_fmt.table;stat_fmt.trade_col='<td class="key">#{trade}</td><td class="value">#{number}</td>';var annex_fn={};function add_annex_fn(a,b){if(annex_fn[a])annex_fn[a].push(b);else annex_fn[a]=[b]}function exec_annex_fn(a){if(a=annex_fn[a])a.each(function(b){b()})}
function init_form(){client_form(kingdom_form_id);client_form(town_form_id);load_fmt();default_kingdom();var a=get_time();density_reaction();a=get_trigger(a);kingdom_events(a);default_town();pop_reaction();town_events(a);exec_annex_fn("init_form")}function get_time(){var a=new Date;return a.getTime()}function get_trigger(a){a=get_time()-a;return a<100?"keyup":"change"}
function default_kingdom(){kingdom_name();$("area").value=roll_dice("2d100 * 1000");$("density").selectedIndex=rand($("density").options.length);$("age").value=roll_dice("2d100 * 10")}function kingdom_events(a){Event.observe("kingdom_name","click",kingdom_name);Event.observe("kingdom",a,kingdom_reaction);Event.observe("area",a,area_reaction);Event.observe("density","change",density_reaction);Event.observe("age",a,age_reaction)}function default_town(){town_name();town_pop("largest")}
function town_events(a){Event.observe("town_name","click",town_name);Event.observe("town",a,town_reaction);Event.observe("town_pop",a,pop_reaction)}function load_fmt(){$$(".stat_fmt").each(function(a){var b=a.readAttribute("data-key");stat_fmt[b]=a.innerHTML.trim()});Object.keys(stat_fmt).each(function(a){stat_fmt[a]=new Template(stat_fmt[a])})}
function kingdom_name(){var a={type:"Kingdom Name",n:1};a={method:"get",parameters:a,onSuccess:function(b){recv_kingdom(b)},onFailure:function(){return false},onException:function(){return false}};new Ajax.Request(rpc_url,a)}function recv_kingdom(a){if(a.responseJSON)list=a.responseJSON;else if(a.responseText)list=a.responseText.evalJSON();else return false;$("kingdom").value=list[0];kingdom_reaction()}
function kingdom_reaction(){kingdom=$("kingdom").value!=""?$("kingdom").value:"Medieval Demographics Calculator";$("kingdom_name").update(kingdom);var a=the_kingdom();$$(".kingdom_name").each(function(b){b.update(a)})}
function the_kingdom(){var a=$("kingdom").value;if(a!="")return(match=/(.+), the (\w+) of /.exec(a))?match[2]+" of "+match[1]:(match=/(.+), the \w+ (\w+)/.exec(a))?match[2]+" of "+match[1]:(match=/(.+), /.exec(a))?"kingdom of "+match[1]:(match=/The (.+)/.exec(a))?match[1]:"kingdom of "+a;return"kingdom"}function area_reaction(){recalc_kingdom()}function density_reaction(){$("ppsm").update($("density").getValue());recalc_kingdom()}
function age_reaction(){var a=the_kingdom(),b=$("area").intValue(),c=$("density").intValue();b=b*c;update_kingdom_castles(a,b)}function recalc_kingdom(){var a=the_kingdom(),b=$("area").intValue(),c=$("density").intValue(),d=b*c;$("physical_area")&&update_kingdom_area(a,b,c);$("population")&&update_kingdom_population(a,d);$("settlements")&&update_kingdom_settlements(a,d);$("castles")&&update_kingdom_castles(a,d);exec_annex_fn("recalc_kingdom")}
function update_kingdom_area(a,b,c){c=c/180+Math.random()*0.1;var d=1-c;a={name:a,area:large_value(b),plow_pct:Math.floor(c*100)+"%",plow_area:large_value(c*b),wild_pct:Math.floor(d*100)+"%",wild_area:large_value(d*b)};update_stat("physical_area",a)}function update_kingdom_population(a,b){a={name:a,total:large_value(b)};update_stat("population",a)}
function update_kingdom_settlements(a,b){b=Math.floor(Math.sqrt(b)*roll_dice("2d4 + 10"));var c=Math.floor(b/100*roll_dice("2d4 * 10"));a={name:a,largest:b,largest_desc:large_value(b),second:c,second_desc:large_value(c)};if(b>8E3){a.desc="city";a.city_note=city_note(c)}else{a.desc="town";a.city_note="There are no other towns of note in the kingdom."}update_stat("settlements",a)}
function city_note(a){for(var b=0;a>8E3;){a=a/100*roll_dice("100 - (2d4 * 5)");a>8E3&&b++}if(b>1){a=(2+b)*roll_dice("2d8");b={cities:b,towns:a}}else{a=2*roll_dice("2d8");b={cities:"no",towns:a}}return stat_fmt.city_note.evaluate(b)}
function update_kingdom_castles(a,b){var c=$("age").intValue(),d=Math.floor(b/5E4);b=Math.floor(b/5E6*Math.sqrt(c));c=Math.floor(d/100*roll_dice("2d4 * 5"));var e=Math.floor(b/100*roll_dice("2d4 * 5"));a={name:a,active:d,ruined:b,active_civ:d-c,ruined_civ:b-e,active_wild:c,ruined_wild:e};update_stat("castles",a)}function update_stat(a,b){$(a).update(stat_fmt[a].evaluate(b))}
function town_name(){var a={type:"Common Town Name",n:1};a={method:"get",parameters:a,onSuccess:function(b){recv_town(b)},onFailure:function(){return false},onException:function(){return false}};new Ajax.Request(rpc_url,a)}function recv_town(a){if(a.responseJSON)list=a.responseJSON;else if(a.responseText)list=a.responseText.evalJSON();else return false;$("town").value=list[0];town_reaction()}
function town_reaction(){town=$("town").value!=""?$("town").value:"Settlement Calculator";$("town_name").update(town);$$(".town_name").each(function(a){a.update(town)})}
function town_pop(a){if(a=="largest")$("town_pop").value=get_pop("largest_city");else if(a=="city")$("town_pop").value=8E3+rand(get_pop("second_city")-8E3);else if(a=="town")$("town_pop").value=roll_dice("(1d7 * 1000) + 1d1000");else if(a=="village")if(rand(2)==0)$("town_pop").value=roll_dice("(1d5 * 50) + 1d50");else $("town_pop").value=roll_dice("(1d49 * 20) + 1d20");else $("town_pop").value=a;pop_reaction()}function get_pop(a){return parseInt($(a).readAttribute("data-town_pop"))}
function pop_reaction(){recalc_town()}function recalc_town(){var a=$("town").value,b=$("town_pop").intValue(),c=town_desc(b);$("town_size")&&update_town_size(a,c,b);$("by_trade")&&update_town_trades(b);$("town_other")&&update_town_other(a,c,b);exec_annex_fn("recalc_town")}function town_desc(a){return a>8E3?"city":a>1E3?"town":"village"}function update_town_size(a,b,c){a={name:a,desc:b,area:Math.round(c/38850*640),total:large_value(c)};update_stat("town_size",a)}
function update_town_trades(a){a=enum_by_trade(a);a={rows:trade_rows(a)};update_stat("by_trade",a)}function enum_by_trade(a){var b={};$H(trade_sv).keys().each(function(c){var d=trade_sv[c];b[c]=enumerate(a,d)});return $H(b)}function enumerate(a,b){var c=0.4+Math.random()*1.2;a=a/b*c;return a>1?{frob:c,number:Math.floor(a)}:Math.random()<a?{frob:c,number:1}:{frob:c,number:0}}
function trade_rows(a){a=trade_cols(a);var b=$("by_trade").getWidth(),c={trade:"&nbsp;",number:"&nbsp;"};c=stat_fmt.trade_col.evaluate(c);return multicol_rows(b,a,c)}function trade_cols(a){return a.keys().sort().map(function(b){var c=a.get(b);c=c.number;if(c==0)c='<span style="color: #dedede;">0</span>';b={trade:b,number:c};return stat_fmt.trade_col.evaluate(b)})}
function update_town_other(a,b,c){a={name:a,desc:b,noble:enum_number(c,200),guard:enum_number(c,150),advocate:enum_number(c,650),clergy:enum_number(c,40),priest:enum_number(c,1E3)};update_stat("town_other",a)}function enum_number(a,b){a=enumerate(a,b);return a.number}function commafy(a){return String(a).replace(/\d(?=(?:\d\d\d)+(?!\d))/g,"$&,")}
function large_value(a){return a=a>1E10?Math.floor(a/1E9)+" billion":a>1E9?Math.floor(a/1E8)/10+" billion":a>1E7?Math.floor(a/1E6)+" million":a>1E6?Math.floor(a/1E5)/10+" million":a>1E4?Math.floor(a/1E3)+" thousand":Math.floor(a)}function nth(a){var b=a%100,c=a%10;return b==11?String(a)+"th":b==12?String(a)+"th":b==13?String(a)+"th":c==1?String(a)+"st":c==2?String(a)+"nd":c==3?String(a)+"rd":String(a)+"th"}document.observe("dom:loaded",init_form);
